"""Use postgresql.ENUM to prevent duplicate type creation

Revision ID: 01e6bbdcf068
Revises: 551945f4ce4b
Create Date: 2025-11-05 22:40:44.296099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01e6bbdcf068'
down_revision: Union[str, Sequence[str], None] = '551945f4ce4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_ref_number', sa.String(), nullable=True),
    sa.Column('tender_title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('employer_name', sa.String(), nullable=True),
    sa.Column('employer_address', sa.Text(), nullable=True),
    sa.Column('issuing_authority', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(), nullable=True),
    sa.Column('bid_security', sa.Numeric(), nullable=True),
    sa.Column('length_km', sa.Numeric(), nullable=True),
    sa.Column('per_km_cost', sa.Numeric(), nullable=True),
    sa.Column('span_length', sa.Numeric(), nullable=True),
    sa.Column('road_work_amount', sa.Numeric(), nullable=True),
    sa.Column('structure_work_amount', sa.Numeric(), nullable=True),
    sa.Column('e_published_date', sa.DateTime(), nullable=True),
    sa.Column('identification_date', sa.DateTime(), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(), nullable=True),
    sa.Column('prebid_meeting_date', sa.DateTime(), nullable=True),
    sa.Column('site_visit_deadline', sa.DateTime(), nullable=True),
    sa.Column('portal_source', sa.String(), nullable=True),
    sa.Column('portal_url', sa.String(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('New', 'Reviewed', 'Shortlisted', 'Bid_Preparation', 'Submitted', 'Won', 'Lost', 'Not_Interested', 'Pending_Results', name='tender_status_enum'), nullable=True),
    sa.Column('review_status', sa.Enum('Not_Reviewed', 'Reviewed', 'Shortlisted', name='review_status_enum'), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_ref_number')
    )
    op.create_table('tender_activity_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='analysisstatusenum'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('analysis_type', sa.String(length=50), nullable=True),
    sa.Column('include_risk_assessment', sa.Boolean(), nullable=True),
    sa.Column('include_rfp_analysis', sa.Boolean(), nullable=True),
    sa.Column('include_scope_of_work', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_analysis_completed_at'), 'tender_analysis', ['completed_at'], unique=False)
    op.create_index(op.f('ix_tender_analysis_status'), 'tender_analysis', ['status'], unique=False)
    op.create_index(op.f('ix_tender_analysis_user_id'), 'tender_analysis', ['user_id'], unique=False)
    op.create_table('tender_comparisons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_1_id', sa.UUID(), nullable=True),
    sa.Column('tender_2_id', sa.UUID(), nullable=True),
    sa.Column('comparison_report', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tender_1_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['tender_2_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('document_type', sa.Enum('Original_RFP', 'Amendment', 'Bid_Document', 'Supporting', 'Comparison_Report', name='tender_doc_type_enum'), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('note_content', sa.Text(), nullable=True),
    sa.Column('parent_note_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_note_id'], ['tender_notes.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_team',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('rfp_analysis_json', sa.JSON(), nullable=True),
    sa.Column('scope_of_work_json', sa.JSON(), nullable=True),
    sa.Column('one_pager_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analysis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_table('analysis_rfp_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('section_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('key_requirements', sa.JSON(), nullable=True),
    sa.Column('estimated_complexity', sa.String(length=20), nullable=False),
    sa.Column('compliance_status', sa.String(length=20), nullable=True),
    sa.Column('compliance_issues', sa.JSON(), nullable=True),
    sa.Column('related_sections', sa.JSON(), nullable=True),
    sa.Column('document_references', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_rfp_sections_analysis_id'), 'analysis_rfp_sections', ['analysis_id'], unique=False)
    op.create_table('analysis_risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('level', postgresql.ENUM('low', 'medium', 'high', 'critical', name='risklevelenum'), nullable=False),
    sa.Column('category', postgresql.ENUM('regulatory', 'financial', 'operational', 'contractual', 'market', name='riskcategoryenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact', sa.String(length=20), nullable=False),
    sa.Column('likelihood', sa.String(length=20), nullable=False),
    sa.Column('mitigation_strategy', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('related_documents', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_risks_analysis_id'), 'analysis_risks', ['analysis_id'], unique=False)
    op.create_table('extraction_quality_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('data_completeness', sa.Float(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('tender_info_confidence', sa.Float(), nullable=True),
    sa.Column('financial_confidence', sa.Float(), nullable=True),
    sa.Column('scope_confidence', sa.Float(), nullable=True),
    sa.Column('rfp_sections_confidence', sa.Float(), nullable=True),
    sa.Column('eligibility_confidence', sa.Float(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('sections_extracted', sa.Integer(), nullable=True),
    sa.Column('tables_extracted', sa.Integer(), nullable=True),
    sa.Column('figures_extracted', sa.Integer(), nullable=True),
    sa.Column('annexures_identified', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analysis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_table('tender_extracted_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('tables', sa.JSON(), nullable=True),
    sa.Column('figures', sa.JSON(), nullable=True),
    sa.Column('extraction_quality', sa.Float(), nullable=True),
    sa.Column('ocr_required', sa.Boolean(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('extractable_sections', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('extraction_started_at', sa.DateTime(), nullable=True),
    sa.Column('extraction_completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analysis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tender_extracted_content')
    op.drop_table('extraction_quality_metrics')
    op.drop_index(op.f('ix_analysis_risks_analysis_id'), table_name='analysis_risks')
    op.drop_table('analysis_risks')
    op.drop_index(op.f('ix_analysis_rfp_sections_analysis_id'), table_name='analysis_rfp_sections')
    op.drop_table('analysis_rfp_sections')
    op.drop_table('analysis_results')
    op.drop_table('tender_team')
    op.drop_table('tender_notes')
    op.drop_table('tender_documents')
    op.drop_table('tender_comparisons')
    op.drop_index(op.f('ix_tender_analysis_user_id'), table_name='tender_analysis')
    op.drop_index(op.f('ix_tender_analysis_status'), table_name='tender_analysis')
    op.drop_index(op.f('ix_tender_analysis_completed_at'), table_name='tender_analysis')
    op.drop_table('tender_analysis')
    op.drop_table('tender_activity_log')
    op.drop_table('tenders')
    # ### end Alembic commands ###
