"""removed analyze submodule

Revision ID: 0eb14aa6a10c
Revises: d920333ade2b
Create Date: 2025-11-05 21:28:16.323303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0eb14aa6a10c'
down_revision: Union[str, Sequence[str], None] = 'd920333ade2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_quality_metrics_analysis_id'), table_name='extraction_quality_metrics')
    op.drop_table('extraction_quality_metrics')
    op.drop_index(op.f('ix_tender_analyses_completed_at'), table_name='tender_analyses')
    op.drop_index(op.f('ix_tender_analyses_created_at'), table_name='tender_analyses')
    op.drop_index(op.f('ix_tender_analyses_status'), table_name='tender_analyses')
    op.drop_index(op.f('ix_tender_analyses_tender_id'), table_name='tender_analyses')
    op.drop_index(op.f('ix_tender_analyses_user_id'), table_name='tender_analyses')
    op.drop_table('tender_analyses')
    op.drop_index(op.f('ix_analysis_rfp_sections_analysis_id'), table_name='analysis_rfp_sections')
    op.drop_table('analysis_rfp_sections')
    op.drop_index(op.f('ix_tender_extracted_content_analysis_id'), table_name='tender_extracted_content')
    op.drop_table('tender_extracted_content')
    op.drop_index(op.f('ix_analysis_risks_analysis_id'), table_name='analysis_risks')
    op.drop_table('analysis_risks')
    op.drop_index(op.f('ix_analysis_results_analysis_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('analysis_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('summary_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('rfp_analysis_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('scope_of_work_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('one_pager_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analyses.id'], name=op.f('analysis_results_analysis_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('analysis_results_pkey'))
    )
    op.create_index(op.f('ix_analysis_results_analysis_id'), 'analysis_results', ['analysis_id'], unique=True)
    op.create_table('analysis_risks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('analysis_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('level', postgresql.ENUM('low', 'medium', 'high', 'critical', name='risklevelenum'), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('regulatory', 'financial', 'operational', 'contractual', 'market', name='riskcategoryenum'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('impact', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('likelihood', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('mitigation_strategy', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommended_action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('related_documents', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analyses.id'], name=op.f('analysis_risks_analysis_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('analysis_risks_pkey'))
    )
    op.create_index(op.f('ix_analysis_risks_analysis_id'), 'analysis_risks', ['analysis_id'], unique=False)
    op.create_table('tender_extracted_content',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('analysis_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sections', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('figures', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('extraction_quality', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ocr_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ocr_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('extractable_sections', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('extraction_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('extraction_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analyses.id'], name=op.f('tender_extracted_content_analysis_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tender_extracted_content_pkey'))
    )
    op.create_index(op.f('ix_tender_extracted_content_analysis_id'), 'tender_extracted_content', ['analysis_id'], unique=True)
    op.create_table('analysis_rfp_sections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('analysis_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('section_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key_requirements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('estimated_complexity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('compliance_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('compliance_issues', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('related_sections', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('document_references', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analyses.id'], name=op.f('analysis_rfp_sections_analysis_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('analysis_rfp_sections_pkey'))
    )
    op.create_index(op.f('ix_analysis_rfp_sections_analysis_id'), 'analysis_rfp_sections', ['analysis_id'], unique=False)
    op.create_table('tender_analyses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='analysisstatusenum'), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_step', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('analysis_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('include_risk_assessment', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('include_rfp_analysis', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('include_scope_of_work', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tender_analyses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tender_analyses_user_id'), 'tender_analyses', ['user_id'], unique=False)
    op.create_index(op.f('ix_tender_analyses_tender_id'), 'tender_analyses', ['tender_id'], unique=False)
    op.create_index(op.f('ix_tender_analyses_status'), 'tender_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_tender_analyses_created_at'), 'tender_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_tender_analyses_completed_at'), 'tender_analyses', ['completed_at'], unique=False)
    op.create_table('extraction_quality_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('analysis_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_completeness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overall_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tender_info_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('financial_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('scope_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rfp_sections_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('eligibility_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('warnings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommendations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sections_extracted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tables_extracted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('figures_extracted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('annexures_identified', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analyses.id'], name=op.f('extraction_quality_metrics_analysis_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('extraction_quality_metrics_pkey'))
    )
    op.create_index(op.f('ix_extraction_quality_metrics_analysis_id'), 'extraction_quality_metrics', ['analysis_id'], unique=True)
    # ### end Alembic commands ###
