"""changed file_references to file_reference

Revision ID: 3894f112b553
Revises: f21bfaa1f787
Create Date: 2025-11-15 18:28:11.583164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3894f112b553'
down_revision: Union[str, Sequence[str], None] = 'f21bfaa1f787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_document_templates', sa.Column('file_reference', sa.String(length=255), nullable=True))
    op.drop_column('analysis_document_templates', 'file_references')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_document_templates', sa.Column('file_references', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('analysis_document_templates', 'file_reference')
    # ### end Alembic commands ###
