"""new alembic update with the latest schemas

Revision ID: 433bd9503863
Revises: bb9b1c128091
Create Date: 2025-11-05 23:29:23.697371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '433bd9503863'
down_revision: Union[str, Sequence[str], None] = 'bb9b1c128091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'parsing', 'analyzing', 'completed', 'failed', name='analysisstatusenum'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status_message', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('analysis_started_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_completed_at', sa.DateTime(), nullable=True),
    sa.Column('one_pager_json', sa.JSON(), nullable=True),
    sa.Column('scope_of_work_json', sa.JSON(), nullable=True),
    sa.Column('data_sheet_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_analysis_status'), 'tender_analysis', ['status'], unique=False)
    op.create_index(op.f('ix_tender_analysis_tender_id'), 'tender_analysis', ['tender_id'], unique=True)
    op.create_table('analysis_document_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_format', sa.String(length=50), nullable=True),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.Column('page_references', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_document_templates_analysis_id'), 'analysis_document_templates', ['analysis_id'], unique=False)
    op.create_table('analysis_rfp_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('section_number', sa.String(length=50), nullable=True),
    sa.Column('section_title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_requirements', sa.JSON(), nullable=True),
    sa.Column('compliance_issues', sa.JSON(), nullable=True),
    sa.Column('page_references', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_rfp_sections_analysis_id'), 'analysis_rfp_sections', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_rfp_sections_analysis_id'), table_name='analysis_rfp_sections')
    op.drop_table('analysis_rfp_sections')
    op.drop_index(op.f('ix_analysis_document_templates_analysis_id'), table_name='analysis_document_templates')
    op.drop_table('analysis_document_templates')
    op.drop_index(op.f('ix_tender_analysis_tender_id'), table_name='tender_analysis')
    op.drop_index(op.f('ix_tender_analysis_status'), table_name='tender_analysis')
    op.drop_table('tender_analysis')
    # ### end Alembic commands ###
