"""Add DMS module tables

Revision ID: 4fe39eb34508
Revises: 52c3fcbe5d56
Create Date: 2025-11-03 00:06:52.376952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fe39eb34508'
down_revision: Union[str, Sequence[str], None] = '52c3fcbe5d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dms_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dms_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_folder_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('confidentiality_level', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_system_folder', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['dms_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dms_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_provider', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('s3_bucket', sa.String(), nullable=True),
    sa.Column('s3_etag', sa.String(), nullable=True),
    sa.Column('s3_version_id', sa.String(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('folder_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidentiality_level', sa.String(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['dms_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dms_folder_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('permission_level', sa.String(), nullable=False),
    sa.Column('inherit_to_subfolders', sa.Boolean(), nullable=True),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['dms_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dms_document_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_level', sa.String(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['dms_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dms_document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('s3_etag', sa.String(), nullable=True),
    sa.Column('s3_version_id', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('change_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['dms_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_category_association',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['dms_categories.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['dms_documents.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_category_association')
    op.drop_table('dms_document_versions')
    op.drop_table('dms_document_permissions')
    op.drop_table('dms_folder_permissions')
    op.drop_table('dms_documents')
    op.drop_table('dms_folders')
    op.drop_table('dms_categories')
    # ### end Alembic commands ###
