"""Add tender action history and wishlist tracking

Revision ID: 7b853ccc95a6
Revises: 433bd9503863
Create Date: 2025-11-06 11:28:46.381620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '7b853ccc95a6'
down_revision: Union[str, Sequence[str], None] = '433bd9503863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_action_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('viewed', 'wishlisted', 'unwishlisted', 'analysis_started', 'analysis_completed', 'shortlisted', 'accepted', 'rejected', name='tenderactionenum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_action_history_tender_id'), 'tender_action_history', ['tender_id'], unique=False)
    op.create_index(op.f('ix_tender_action_history_user_id'), 'tender_action_history', ['user_id'], unique=False)
    op.add_column('tenders', sa.Column('is_wishlisted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_tenders_is_wishlisted'), 'tenders', ['is_wishlisted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenders_is_wishlisted'), table_name='tenders')
    op.drop_column('tenders', 'is_wishlisted')
    op.drop_index(op.f('ix_tender_action_history_user_id'), table_name='tender_action_history')
    op.drop_index(op.f('ix_tender_action_history_tender_id'), table_name='tender_action_history')
    op.drop_table('tender_action_history')
    # ### end Alembic commands ###
