"""added cascading deletes

Revision ID: 8510f89a1838
Revises: 126b3d082b95
Create Date: 2025-11-18 04:29:32.397694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '8510f89a1838'
down_revision: Union[str, Sequence[str], None] = '126b3d082b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('analysis_document_templates_analysis_id_fkey'), 'analysis_document_templates', type_='foreignkey')
    op.create_foreign_key(None, 'analysis_document_templates', 'tender_analysis', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('analysis_rfp_sections_analysis_id_fkey'), 'analysis_rfp_sections', type_='foreignkey')
    op.create_foreign_key(None, 'analysis_rfp_sections', 'tender_analysis', ['analysis_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis_rfp_sections', type_='foreignkey')
    op.create_foreign_key(op.f('analysis_rfp_sections_analysis_id_fkey'), 'analysis_rfp_sections', 'tender_analysis', ['analysis_id'], ['id'])
    op.drop_constraint(None, 'analysis_document_templates', type_='foreignkey')
    op.create_foreign_key(op.f('analysis_document_templates_analysis_id_fkey'), 'analysis_document_templates', 'tender_analysis', ['analysis_id'], ['id'])
    # ### end Alembic commands ###
