"""Fix incorrect relationship cascades for tender analysis

Revision ID: 924eee2a34fd
Revises: 7baeffc3bed1
Create Date: 2025-11-05 15:53:09.468159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '924eee2a34fd'
down_revision: Union[str, Sequence[str], None] = '7baeffc3bed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
