"""Add user_id and chat_id to tender analysis

Revision ID: b11b25cdcd86
Revises: 42d94f60828c
Create Date: 2025-11-06 13:38:41.260593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'b11b25cdcd86'
down_revision: Union[str, Sequence[str], None] = '42d94f60828c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender_analysis', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('tender_analysis', sa.Column('chat_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tender_analysis_user_id'), 'tender_analysis', ['user_id'], unique=False)
    op.create_foreign_key(None, 'tender_analysis', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tender_analysis', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tender_analysis', type_='foreignkey')
    op.drop_constraint(None, 'tender_analysis', type_='foreignkey')
    op.drop_index(op.f('ix_tender_analysis_user_id'), table_name='tender_analysis')
    op.drop_column('tender_analysis', 'chat_id')
    op.drop_column('tender_analysis', 'user_id')
    # ### end Alembic commands ###
