"""Phase 1: Add tender document extraction and quality tracking tables

Revision ID: d98bbf667f83
Revises: 48317806289f
Create Date: 2025-11-05 15:11:45.747765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'd98bbf667f83'
down_revision: Union[str, Sequence[str], None] = '48317806289f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_extracted_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('tables', sa.JSON(), nullable=True),
    sa.Column('figures', sa.JSON(), nullable=True),
    sa.Column('extraction_quality', sa.Float(), nullable=True),
    sa.Column('ocr_required', sa.Boolean(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('extractable_sections', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('extraction_started_at', sa.DateTime(), nullable=True),
    sa.Column('extraction_completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_extracted_content_analysis_id'), 'tender_extracted_content', ['analysis_id'], unique=True)
    op.create_table('extraction_quality_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('data_completeness', sa.Float(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('tender_info_confidence', sa.Float(), nullable=True),
    sa.Column('financial_confidence', sa.Float(), nullable=True),
    sa.Column('scope_confidence', sa.Float(), nullable=True),
    sa.Column('rfp_sections_confidence', sa.Float(), nullable=True),
    sa.Column('eligibility_confidence', sa.Float(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('sections_extracted', sa.Integer(), nullable=True),
    sa.Column('tables_extracted', sa.Integer(), nullable=True),
    sa.Column('figures_extracted', sa.Integer(), nullable=True),
    sa.Column('annexures_identified', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_quality_metrics_analysis_id'), 'extraction_quality_metrics', ['analysis_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_quality_metrics_analysis_id'), table_name='extraction_quality_metrics')
    op.drop_table('extraction_quality_metrics')
    op.drop_index(op.f('ix_tender_extracted_content_analysis_id'), table_name='tender_extracted_content')
    op.drop_table('tender_extracted_content')
    # ### end Alembic commands ###
