"""new alembic

Revision ID: db4144e8ac78
Revises: 
Create Date: 2025-11-07 01:49:39.325734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db4144e8ac78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('drive_folders', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dms_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dms_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_folder_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('confidentiality_level', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_system_folder', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['dms_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processing_stats', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('tender_release_date', sa.Date(), nullable=False),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('no_of_new_tenders', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_runs_run_at'), 'scrape_runs', ['run_at'], unique=False)
    op.create_index(op.f('ix_scrape_runs_tender_release_date'), 'scrape_runs', ['tender_release_date'], unique=False)
    op.create_table('token_blocklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blocklist_jti'), 'token_blocklist', ['jti'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('account_status', sa.Enum('Active', 'Inactive', 'Locked', 'Pending', name='user_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_password_change', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('password_expiry_date', sa.Date(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('action_description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('Success', 'Failed', 'Partial', name='audit_status_enum'), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_document_association',
    sa.Column('chat_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], )
    )
    op.create_table('dms_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_provider', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('s3_bucket', sa.String(), nullable=True),
    sa.Column('s3_etag', sa.String(), nullable=True),
    sa.Column('s3_version_id', sa.String(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('folder_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidentiality_level', sa.String(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('is_tender_file', sa.Boolean(), nullable=True),
    sa.Column('is_cached', sa.Boolean(), nullable=True),
    sa.Column('cache_status', sa.String(), nullable=True),
    sa.Column('cache_error', sa.Text(), nullable=True),
    sa.Column('scraped_tender_file_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['dms_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dms_folder_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('permission_level', sa.String(), nullable=False),
    sa.Column('inherit_to_subfolders', sa.Boolean(), nullable=True),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['dms_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('login_timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('Success', 'Failed', name='login_status_enum'), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('module_name', sa.String(), nullable=True),
    sa.Column('access_type', sa.Enum('Default', 'Admin-Granted', name='access_type_enum'), nullable=True),
    sa.Column('granted_by_id', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('access_reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraped_email_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_uid', sa.String(), nullable=False),
    sa.Column('email_sender', sa.String(), nullable=False),
    sa.Column('email_received_at', sa.DateTime(), nullable=False),
    sa.Column('tender_url', sa.String(), nullable=False),
    sa.Column('tender_id', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('scrape_run_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_received_at', 'scraped_email_logs', ['email_received_at'], unique=False)
    op.create_index('idx_email_uid_tender_url', 'scraped_email_logs', ['email_uid', 'tender_url'], unique=True)
    op.create_index('idx_tender_url', 'scraped_email_logs', ['tender_url'], unique=False)
    op.create_index('idx_tender_url_priority', 'scraped_email_logs', ['tender_url', 'priority'], unique=False)
    op.create_index(op.f('ix_scraped_email_logs_email_received_at'), 'scraped_email_logs', ['email_received_at'], unique=False)
    op.create_index(op.f('ix_scraped_email_logs_email_uid'), 'scraped_email_logs', ['email_uid'], unique=False)
    op.create_index(op.f('ix_scraped_email_logs_tender_url'), 'scraped_email_logs', ['tender_url'], unique=False)
    op.create_table('scraped_tender_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_name', sa.String(), nullable=True),
    sa.Column('number_of_tenders', sa.String(), nullable=True),
    sa.Column('scrape_run_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_tender_queries_query_name'), 'scraped_tender_queries', ['query_name'], unique=False)
    op.create_table('tender_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('chat_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'parsing', 'analyzing', 'completed', 'failed', name='analysisstatusenum'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status_message', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('analysis_started_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_completed_at', sa.DateTime(), nullable=True),
    sa.Column('one_pager_json', sa.JSON(), nullable=True),
    sa.Column('scope_of_work_json', sa.JSON(), nullable=True),
    sa.Column('data_sheet_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_analysis_status'), 'tender_analysis', ['status'], unique=False)
    op.create_index(op.f('ix_tender_analysis_tender_id'), 'tender_analysis', ['tender_id'], unique=True)
    op.create_index(op.f('ix_tender_analysis_user_id'), 'tender_analysis', ['user_id'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_ref_number', sa.String(), nullable=True),
    sa.Column('tender_title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('employer_name', sa.String(), nullable=True),
    sa.Column('employer_address', sa.Text(), nullable=True),
    sa.Column('issuing_authority', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(), nullable=True),
    sa.Column('bid_security', sa.Numeric(), nullable=True),
    sa.Column('length_km', sa.Numeric(), nullable=True),
    sa.Column('per_km_cost', sa.Numeric(), nullable=True),
    sa.Column('span_length', sa.Numeric(), nullable=True),
    sa.Column('road_work_amount', sa.Numeric(), nullable=True),
    sa.Column('structure_work_amount', sa.Numeric(), nullable=True),
    sa.Column('e_published_date', sa.DateTime(), nullable=True),
    sa.Column('identification_date', sa.DateTime(), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(), nullable=True),
    sa.Column('prebid_meeting_date', sa.DateTime(), nullable=True),
    sa.Column('site_visit_deadline', sa.DateTime(), nullable=True),
    sa.Column('portal_source', sa.String(), nullable=True),
    sa.Column('portal_url', sa.String(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('New', 'Reviewed', 'Shortlisted', 'Bid_Preparation', 'Submitted', 'Won', 'Lost', 'Not_Interested', 'Pending_Results', name='tender_status_enum'), nullable=True),
    sa.Column('review_status', sa.Enum('Not_Reviewed', 'Reviewed', 'Shortlisted', name='review_status_enum'), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('is_wishlisted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_ref_number')
    )
    op.create_index(op.f('ix_tenders_is_wishlisted'), 'tenders', ['is_wishlisted'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_document_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_format', sa.String(length=50), nullable=True),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.Column('page_references', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_document_templates_analysis_id'), 'analysis_document_templates', ['analysis_id'], unique=False)
    op.create_table('analysis_rfp_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('section_number', sa.String(length=50), nullable=True),
    sa.Column('section_title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_requirements', sa.JSON(), nullable=True),
    sa.Column('compliance_issues', sa.JSON(), nullable=True),
    sa.Column('page_references', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_rfp_sections_analysis_id'), 'analysis_rfp_sections', ['analysis_id'], unique=False)
    op.create_table('dms_document_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_level', sa.String(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['dms_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dms_document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('s3_etag', sa.String(), nullable=True),
    sa.Column('s3_version_id', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('change_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['dms_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_category_association',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['dms_categories.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['dms_documents.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'category_id')
    )
    op.create_table('scraped_tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id_str', sa.String(), nullable=True),
    sa.Column('tender_name', sa.String(), nullable=True),
    sa.Column('tender_url', sa.String(), nullable=True),
    sa.Column('dms_folder_id', sa.UUID(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('analysis_status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('query_id', sa.UUID(), nullable=True),
    sa.Column('tdr', sa.String(), nullable=True),
    sa.Column('tendering_authority', sa.String(), nullable=True),
    sa.Column('tender_no', sa.String(), nullable=True),
    sa.Column('tender_id_detail', sa.String(), nullable=True),
    sa.Column('tender_brief', sa.Text(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('document_fees', sa.String(), nullable=True),
    sa.Column('emd', sa.String(), nullable=True),
    sa.Column('tender_value', sa.String(), nullable=True),
    sa.Column('tender_type', sa.String(), nullable=True),
    sa.Column('bidding_type', sa.String(), nullable=True),
    sa.Column('competition_type', sa.String(), nullable=True),
    sa.Column('tender_details', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.String(), nullable=True),
    sa.Column('last_date_of_bid_submission', sa.String(), nullable=True),
    sa.Column('tender_opening_date', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('information_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['scraped_tender_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_tenders_tender_id_str'), 'scraped_tenders', ['tender_id_str'], unique=False)
    op.create_table('tender_action_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('viewed', 'wishlisted', 'unwishlisted', 'analysis_started', 'analysis_completed', 'shortlisted', 'accepted', 'rejected', name='tenderactionenum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_action_history_tender_id'), 'tender_action_history', ['tender_id'], unique=False)
    op.create_index(op.f('ix_tender_action_history_user_id'), 'tender_action_history', ['user_id'], unique=False)
    op.create_table('tender_activity_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_comparisons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_1_id', sa.UUID(), nullable=True),
    sa.Column('tender_2_id', sa.UUID(), nullable=True),
    sa.Column('comparison_report', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tender_1_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['tender_2_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('document_type', sa.Enum('Original_RFP', 'Amendment', 'Bid_Document', 'Supporting', 'Comparison_Report', name='tender_doc_type_enum'), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('note_content', sa.Text(), nullable=True),
    sa.Column('parent_note_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_note_id'], ['tender_notes.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_team',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraped_tender_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_description', sa.String(), nullable=True),
    sa.Column('file_size', sa.String(), nullable=True),
    sa.Column('dms_path', sa.String(), nullable=False),
    sa.Column('is_cached', sa.Boolean(), nullable=False),
    sa.Column('cache_status', sa.String(), nullable=False),
    sa.Column('cache_error', sa.Text(), nullable=True),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['scraped_tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraped_tender_files')
    op.drop_table('tender_team')
    op.drop_table('tender_notes')
    op.drop_table('tender_documents')
    op.drop_table('tender_comparisons')
    op.drop_table('tender_activity_log')
    op.drop_index(op.f('ix_tender_action_history_user_id'), table_name='tender_action_history')
    op.drop_index(op.f('ix_tender_action_history_tender_id'), table_name='tender_action_history')
    op.drop_table('tender_action_history')
    op.drop_index(op.f('ix_scraped_tenders_tender_id_str'), table_name='scraped_tenders')
    op.drop_table('scraped_tenders')
    op.drop_table('document_category_association')
    op.drop_table('dms_document_versions')
    op.drop_table('dms_document_permissions')
    op.drop_index(op.f('ix_analysis_rfp_sections_analysis_id'), table_name='analysis_rfp_sections')
    op.drop_table('analysis_rfp_sections')
    op.drop_index(op.f('ix_analysis_document_templates_analysis_id'), table_name='analysis_document_templates')
    op.drop_table('analysis_document_templates')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_tenders_is_wishlisted'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_tender_analysis_user_id'), table_name='tender_analysis')
    op.drop_index(op.f('ix_tender_analysis_tender_id'), table_name='tender_analysis')
    op.drop_index(op.f('ix_tender_analysis_status'), table_name='tender_analysis')
    op.drop_table('tender_analysis')
    op.drop_index(op.f('ix_scraped_tender_queries_query_name'), table_name='scraped_tender_queries')
    op.drop_table('scraped_tender_queries')
    op.drop_index(op.f('ix_scraped_email_logs_tender_url'), table_name='scraped_email_logs')
    op.drop_index(op.f('ix_scraped_email_logs_email_uid'), table_name='scraped_email_logs')
    op.drop_index(op.f('ix_scraped_email_logs_email_received_at'), table_name='scraped_email_logs')
    op.drop_index('idx_tender_url_priority', table_name='scraped_email_logs')
    op.drop_index('idx_tender_url', table_name='scraped_email_logs')
    op.drop_index('idx_email_uid_tender_url', table_name='scraped_email_logs')
    op.drop_index('idx_email_received_at', table_name='scraped_email_logs')
    op.drop_table('scraped_email_logs')
    op.drop_table('module_access')
    op.drop_table('messages')
    op.drop_table('login_history')
    op.drop_table('document_chunks')
    op.drop_table('dms_folder_permissions')
    op.drop_table('dms_documents')
    op.drop_table('chat_document_association')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_blocklist_jti'), table_name='token_blocklist')
    op.drop_table('token_blocklist')
    op.drop_index(op.f('ix_scrape_runs_tender_release_date'), table_name='scrape_runs')
    op.drop_index(op.f('ix_scrape_runs_run_at'), table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_table('documents')
    op.drop_table('dms_folders')
    op.drop_table('dms_categories')
    op.drop_table('chats')
    # ### end Alembic commands ###
