"""Remove all tenderiq analysis tables and enums

Revision ID: e066d8673da4
Revises: 01e6bbdcf068
Create Date: 2025-11-05 22:48:40.543530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'e066d8673da4'
down_revision: Union[str, Sequence[str], None] = '01e6bbdcf068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_ref_number', sa.String(), nullable=True),
    sa.Column('tender_title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('employer_name', sa.String(), nullable=True),
    sa.Column('employer_address', sa.Text(), nullable=True),
    sa.Column('issuing_authority', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(), nullable=True),
    sa.Column('bid_security', sa.Numeric(), nullable=True),
    sa.Column('length_km', sa.Numeric(), nullable=True),
    sa.Column('per_km_cost', sa.Numeric(), nullable=True),
    sa.Column('span_length', sa.Numeric(), nullable=True),
    sa.Column('road_work_amount', sa.Numeric(), nullable=True),
    sa.Column('structure_work_amount', sa.Numeric(), nullable=True),
    sa.Column('e_published_date', sa.DateTime(), nullable=True),
    sa.Column('identification_date', sa.DateTime(), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(), nullable=True),
    sa.Column('prebid_meeting_date', sa.DateTime(), nullable=True),
    sa.Column('site_visit_deadline', sa.DateTime(), nullable=True),
    sa.Column('portal_source', sa.String(), nullable=True),
    sa.Column('portal_url', sa.String(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('New', 'Reviewed', 'Shortlisted', 'Bid_Preparation', 'Submitted', 'Won', 'Lost', 'Not_Interested', 'Pending_Results', name='tender_status_enum'), nullable=True),
    sa.Column('review_status', sa.Enum('Not_Reviewed', 'Reviewed', 'Shortlisted', name='review_status_enum'), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_ref_number')
    )
    op.create_table('tender_activity_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_comparisons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_1_id', sa.UUID(), nullable=True),
    sa.Column('tender_2_id', sa.UUID(), nullable=True),
    sa.Column('comparison_report', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tender_1_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['tender_2_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('document_type', sa.Enum('Original_RFP', 'Amendment', 'Bid_Document', 'Supporting', 'Comparison_Report', name='tender_doc_type_enum'), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('note_content', sa.Text(), nullable=True),
    sa.Column('parent_note_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_note_id'], ['tender_notes.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_team',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tender_team')
    op.drop_table('tender_notes')
    op.drop_table('tender_documents')
    op.drop_table('tender_comparisons')
    op.drop_table('tender_activity_log')
    op.drop_table('tenders')
    # ### end Alembic commands ###
