"""new column in analysis_document_templates

Revision ID: f21bfaa1f787
Revises: 397ef50250fe
Create Date: 2025-11-15 18:21:02.455766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f21bfaa1f787'
down_revision: Union[str, Sequence[str], None] = '397ef50250fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_document_templates', sa.Column('file_references', sa.JSON(), nullable=False))
    op.alter_column('analysis_document_templates', 'page_references',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_document_templates', 'page_references',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('analysis_document_templates', 'file_references')
    # ### end Alembic commands ###
