"""updated new schema files

Revision ID: f3704f4161e5
Revises: db4144e8ac78
Create Date: 2025-11-10 22:01:47.528514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'f3704f4161e5'
down_revision: Union[str, Sequence[str], None] = 'db4144e8ac78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_wishlist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tender_ref_number', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('authority', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('emd', sa.Float(), nullable=False),
    sa.Column('due_date', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('analysis_state', sa.Boolean(), nullable=True),
    sa.Column('synopsis_state', sa.Boolean(), nullable=True),
    sa.Column('evaluated_state', sa.Boolean(), nullable=True),
    sa.Column('results', sa.String(length=50), nullable=True),
    sa.Column('status_message', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('added_to_wishlist_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tender_ref_number'], ['tenders.tender_ref_number'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_wishlist_id'), 'tender_wishlist', ['id'], unique=False)
    op.create_index(op.f('ix_tender_wishlist_tender_ref_number'), 'tender_wishlist', ['tender_ref_number'], unique=False)
    op.create_index(op.f('ix_tender_wishlist_user_id'), 'tender_wishlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_wishlist_user_id'), table_name='tender_wishlist')
    op.drop_index(op.f('ix_tender_wishlist_tender_ref_number'), table_name='tender_wishlist')
    op.drop_index(op.f('ix_tender_wishlist_id'), table_name='tender_wishlist')
    op.drop_table('tender_wishlist')
    # ### end Alembic commands ###
